SET FOREIGN_KEY_CHECKS = 0;

REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (1, 1, 'Raíz', 'Catálogo raíz del sistema', 'ROOT', 0, '2025-06-24 21:59:38.000000', NULL, NULL, NULL, NULL, NULL, NULL, 'SYSTEM', NULL, NULL, 0);
REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (2, 1, 'PermisoTipo1', 'Permiso de Tipo 1', 'PT1', 0, '2025-06-24 22:17:05.335055', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (3, 1, 'PermisoTipo2', 'Permiso de Tipo 2', 'PT2', 0, '2025-06-24 22:18:05.335055', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (4, 1, 'Pendiente', 'Pedido en espera', 'PENDIENTE', 0, '2025-07-01 22:18:05.335055', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (5, 1, 'Completado', 'Pedido completado', 'COMPLETADO', 0, '2025-07-01 22:18:05.335055', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `catalogos` (`Id`, `IdPadre`, `Nombre`, `Descripcion`, `Nemonico`, `Valor`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (6, 1, 'Anulado', 'Pedido anulado', 'ANULADO', 0, '2025-07-01 22:18:05.335055', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `empresas` (`Id`, `Nombre`, `Nemonico`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (1, 'Empresa 1', 'Empr1', '2025-06-24 22:05:35.878026', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `menus` (`Id`, `IdPadre`, `Nombre`, `Nemonico`, `Descripcion`, `VerificaPermiso`, `Orden`, `Url`, `IdTipo`, `IdEmpresa`, `IdPermiso`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (1, NULL, 'menu 1', 'menu1', 'Menú 1', 0, 0, 'string', 4, 1, NULL, '2025-06-24 22:23:06.835006', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `menus` (`Id`, `IdPadre`, `Nombre`, `Nemonico`, `Descripcion`, `VerificaPermiso`, `Orden`, `Url`, `IdTipo`, `IdEmpresa`, `IdPermiso`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (2, NULL, 'menu 2', 'menu2', 'Menú 2', 1, 0, 'string', 4, 1, 1, '2025-06-24 22:24:22.774882', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `permisos` (`Id`, `Nemonico`, `Descripcion`, `IdTipo`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (1, 'general', 'Permiso General', 2, '2025-06-24 22:17:50.030821', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `roles` (`Id`, `Nombre`, `Descripcion`, `IdEmpresa`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (1, 'administrador', 'Rol de Administrador', 1, '2025-06-24 22:13:47.626240', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `usuarios` (`Id`, `User`, `PasswordHash`, `Nombres`, `Apellidos`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (1, 'admin', 'JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=', 'admin', 'admin', '2025-06-24 22:03:21.865606', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `pantallas` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `VerificaPermiso`, `IdMenu`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (1, 'pantalla 1', 'pantalla1', 'Pantalla 1', 0, 1, '2025-06-24 22:30:52.672868', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `pantallas` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `VerificaPermiso`, `IdMenu`, `FechaCreacion`, `FechaEliminacion`, `FechaModificacion`, `IpCreacion`, `IpEliminacion`, `IpModificacion`, `Removido`, `Token`, `UsuarioCreacion`, `UsuarioEliminacion`, `UsuarioModificacion`) VALUES (2, 'pantalla 2', 'pantalla2', 'Pantalla 2', 1, 2, '2025-06-24 22:31:06.777951', NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0, NULL, NULL, NULL, NULL);
REPLACE INTO `cartas` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `IdEmpresa`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (1, 'Carta 1', 'Carta1', 'Carta 1', 1, '2025-06-30 21:01:56.357762', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `cartas` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `IdEmpresa`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (2, 'Carta 2', 'carta2', 'Carta 2', 1, '2025-06-30 21:06:46.518261', '2025-06-30 21:08:36.052182', NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', 'IP.PRUEBA', NULL, 0);
REPLACE INTO `cartas` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `IdEmpresa`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (3, 'Carta3', 'carta3', 'Carta 3', 1, '2025-06-30 21:07:45.257824', NULL, '2025-06-30 21:08:53.048203', NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, 'IP.PRUEBA', 1);
REPLACE INTO `itemscarta` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `Precio`, `IdCategoria`, `IdCarta`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (1, 'hamburguesa', 'burger1', 'hamburguesa con carne, jamon, queso, y una porcion de papas', 0, 1, 1, '2025-06-30 21:30:33.373364', NULL, NULL, NULL, NULL, NULL, NULL, 'IP.PRUEBA', NULL, NULL, 0);
REPLACE INTO `itemscarta` (`Id`, `Nombre`, `Nemonico`, `Descripcion`, `Precio`, `IdCategoria`, `IdCarta`, `FechaCreacion`, `FechaModificacion`, `FechaEliminacion`, `UsuarioCreacion`, `UsuarioModificacion`, `UsuarioEliminacion`, `Token`, `IpCreacion`, `IpModificacion`, `IpEliminacion`, `Removido`) VALUES (2, 'hamburguesota completa', 'burger2', 'hamburguesa con carne, tocino, huevo, jamon, queso, y una porcion de papas', 0, 1, 1, '2025-06-30 21:31:48.734397', '2025-06-30 21:32:09.376070', '2025-06-30 21:32:40.491261', NULL, NULL, NULL, NULL, 'IP.PRUEBA', 'IP.PRUEBA', 'IP.PRUEBA', 0);

SET FOREIGN_KEY_CHECKS = 1;
